update template

diff --git a/.github/workflows/droplet-deploy.yml b/.github/workflows/droplet-deploy.yml
--- a/.github/workflows/droplet-deploy.yml
+++ b/.github/workflows/droplet-deploy.yml
@@ -164,22 +164,26 @@ jobs:
                   log_content=\$(cat /home/${{ env.APP_USER }}/log/provision-droplet-init.log | tr -d '\r\n')
                   if [[ \$log_content == 'succeed' ]]; then
                     echo 'true'
-                  else
+                  elif [[ \$log_content == 'fail' ]]; then
                     echo 'false'
                   fi
                 else
-                  echo 'false'
+                  echo 'null'
                 fi
-              " || echo "false")
+              " || echo "null")
 
             # Check if the file was found and break if so
             if [[ $init_succeed == "true" ]]; then
               echo "Init script validation succeeded on attempt $i."
               break
+            elif [ $init_succeed == "false" ]; then
+              echo "Init script validation failed on attempt $i."
+              break
             fi
 
             # Wait before retrying
-            echo "Attempt $i/12: Init script log file not found or validation failed. Retrying in 10 seconds..."
+            echo "Attempt $i/12: Init log not found(script probably still running)."
+            echo "Retrying in 10 seconds..."
             sleep 10
           done
 
