update template

diff --git a/.github/workflows/droplet-deploy.yml b/.github/workflows/droplet-deploy.yml
--- a/.github/workflows/droplet-deploy.yml
+++ b/.github/workflows/droplet-deploy.yml
@@ -62,7 +62,7 @@ jobs:
       - name: Configure Github ssh access to droplet
         run: |
           mkdir -p ~/.ssh
-          echo "${{ secrets.DROPLET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          echo "${{ secrets.GH_TO_DROPLET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
 
       - name: Get droplet info (Check if droplet with name exists)
@@ -113,7 +113,7 @@ jobs:
           chmod 644 ~/.ssh/known_hosts
 
           # validate can ssh
-          # ssh -o BatchMode=yes -o ConnectTimeout=10 root@${{ env.droplet_ip }} "echo SSH connection successful" || (echo "SSH connection failed" && exit 1)
+          ssh -o BatchMode=yes -o ConnectTimeout=10 root@${{ env.droplet_ip }} "echo SSH connection successful" || (echo "SSH connection failed" && exit 1)
 
           echo "Re-provision droplet base image (./user-data-script-ready.sh)"
           script_contents=$(cat ./user-data-script-ready.sh)
