update template

diff --git a/.github/workflows/droplet-deploy.yml b/.github/workflows/droplet-deploy.yml
--- a/.github/workflows/droplet-deploy.yml
+++ b/.github/workflows/droplet-deploy.yml
@@ -94,6 +94,12 @@ jobs:
             --user-data-file ./user-data-script-ready.sh \
             --wait
 
+          # validate init script succeeded
+          doctl compute ssh ${{ env.DROPLET_NAME }} \
+            --ssh-user ${{ env.APP_USER }} \
+            --ssh-key-path ~/.ssh/id_rsa \
+            --ssh-command "if [[ \$(cat /home/${APP_USER}/log/provision-droplet-init.log) == 'succeed' ]]; then echo 'init script succeeded!' && exit 0; else exit 1; fi"
+
       - name: Get Droplet IP Address
         id: droplet_ip
         run: |
@@ -107,18 +113,18 @@ jobs:
             echo "droplet_ip=$droplet_ip" >> vars.env
           fi
 
-      - name: Re-provision droplet base image (if exists)
-        if: ${{ env.droplet_exists == 'true' }}
+      - name: Configure github ssh access to droplet
         run: |
           mkdir -p ~/.ssh
           echo "${{ secrets.GH_TO_DROPLET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
           chmod 600 ~/.ssh/id_rsa
           ssh-keyscan -H ${{ env.droplet_ip }} >> ~/.ssh/known_hosts
           chmod 644 ~/.ssh/known_hosts
+          # ssh -o BatchMode=yes -o ConnectTimeout=10 ${{ env.APP_USER }}@${{ env.droplet_ip }} "echo SSH connection successful" || (echo "SSH connection failed" && exit 1)
 
-          # validate can ssh
-          ssh -o BatchMode=yes -o ConnectTimeout=10 ${{ env.APP_USER }}@${{ env.droplet_ip }} "echo SSH connection successful" || (echo "SSH connection failed" && exit 1)
-
+      - name: Re-provision droplet base image (if exists)
+        if: ${{ env.droplet_exists == 'true' }}
+        run: |
           echo "Re-provision droplet base image (./user-data-script-ready.sh)"
           script_contents=$(cat ./user-data-script-ready.sh)
           doctl compute ssh ${{ env.DROPLET_NAME }} \
@@ -126,16 +132,18 @@ jobs:
             --ssh-key-path ~/.ssh/id_rsa \
             --ssh-command "sudo bash -c '$script_contents'"
 
-          # validate init script succeeded
-          doctl compute ssh ${{ env.DROPLET_NAME }} \
-            --ssh-user ${{ env.APP_USER }} \
-            --ssh-key-path ~/.ssh/id_rsa \
-            --ssh-command "if [[ \$(cat /home/${APP_USER}/log/provision-droplet-init.log) == 'succeed' ]]; then exit 0; else exit 1; fi"
-
       - name: Wait for newly created droplet to be ready for ssh connections
         if: ${{ env.droplet_exists == 'false' }}
         run: |
           sleep 180
+
+      - name: Validate init script succeeded
+        run: |
+          # validate init script succeeded
+          doctl compute ssh ${{ env.DROPLET_NAME }} \
+            --ssh-user ${{ env.APP_USER }} \
+            --ssh-key-path ~/.ssh/id_rsa \
+            --ssh-command "if [[ \$(cat /home/${APP_USER}/log/provision-droplet-init.log) == 'succeed' ]]; then echo 'init script succeeded!' && exit 0; else exit 1; fi"
 
       - name: Remove Existing Configuration File
         uses: appleboy/ssh-action@v0.1.7
