update template

diff --git a/.github/workflows/droplet-deploy.yml b/.github/workflows/droplet-deploy.yml
--- a/.github/workflows/droplet-deploy.yml
+++ b/.github/workflows/droplet-deploy.yml
@@ -106,6 +106,15 @@ jobs:
         run: |
           sleep 180
 
+      - name: Configure github ssh access to droplet
+        run: |
+          mkdir -p ~/.ssh
+          echo "${{ secrets.GH_TO_DROPLET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
+          chmod 600 ~/.ssh/id_rsa
+          ssh-keyscan -H ${{ env.droplet_ip }} >> ~/.ssh/known_hosts
+          chmod 644 ~/.ssh/known_hosts
+          # ssh -o BatchMode=yes -o ConnectTimeout=10 ${{ env.APP_USER }}@${{ env.droplet_ip }} "echo SSH connection successful" || (echo "SSH connection failed" && exit 1)
+
       - name: Remove Existing Configuration File
         uses: appleboy/ssh-action@v0.1.7
         with:
@@ -134,15 +143,6 @@ jobs:
             -o StrictHostKeyChecking=no \
             droplet-config.yml \
             ${{ env.APP_USER }}@${{ env.droplet_ip }}:/home/${{ env.APP_USER }}/
-
-      - name: Configure github ssh access to droplet
-        run: |
-          mkdir -p ~/.ssh
-          echo "${{ secrets.GH_TO_DROPLET_PRIVATE_KEY }}" > ~/.ssh/id_rsa
-          chmod 600 ~/.ssh/id_rsa
-          ssh-keyscan -H ${{ env.droplet_ip }} >> ~/.ssh/known_hosts
-          chmod 644 ~/.ssh/known_hosts
-          # ssh -o BatchMode=yes -o ConnectTimeout=10 ${{ env.APP_USER }}@${{ env.droplet_ip }} "echo SSH connection successful" || (echo "SSH connection failed" && exit 1)
 
       - name: Re-provision droplet base os (if droplet exists)
         if: ${{ env.droplet_exists == 'true' }}
