update template

diff --git a/.github/workflows/droplet-deploy.yml b/.github/workflows/droplet-deploy.yml
--- a/.github/workflows/droplet-deploy.yml
+++ b/.github/workflows/droplet-deploy.yml
@@ -117,6 +117,18 @@ jobs:
     runs-on: ubuntu-latest
     needs: create-droplet
     steps:
+      - name: Get Droplet IP Address
+        id: droplet_ip
+        run: |
+          droplet_ip=$(doctl compute droplet list --format "Name,PublicIPv4" --no-header | grep "${{ env.DROPLET_NAME }}" | awk '{print $2}' | head -n 1)
+          if [ -z "$droplet_ip" ]; then
+            echo "Droplet IP not found"
+            exit 1
+          else
+            echo "Droplet IP found: $droplet_ip"
+            echo "droplet_ip=$droplet_ip" >> $GITHUB_ENV
+          fi
+
       - name: Run Ansible Playbook
         uses: appleboy/ssh-action@v0.1.7
         with:
